(cl:in-package cartographer_ros_msgs-msg)
(cl:export '(CURRENT_BAGFILE_NAME-VAL
          CURRENT_BAGFILE_NAME
          CURRENT_BAGFILE_ID-VAL
          CURRENT_BAGFILE_ID
          TOTAL_BAGFILES-VAL
          TOTAL_BAGFILES
          TOTAL_MESSAGES-VAL
          TOTAL_MESSAGES
          PROCESSED_MESSAGES-VAL
          PROCESSED_MESSAGES
          TOTAL_SECONDS-VAL
          TOTAL_SECONDS
          PROCESSED_SECONDS-VAL
          PROCESSED_SECONDS
))