(cl:in-package cartographer_ros_msgs-srv)
(cl:export '(CONFIGURATION_DIRECTORY-VAL
          CONFIGURATION_DIRECTORY
          CONFIGURATION_BASENAME-VAL
          CONFIGURATION_BASENAME
          USE_INITIAL_POSE-VAL
          USE_INITIAL_POSE
          INITIAL_POSE-VAL
          INITIAL_POSE
          RELATIVE_TO_TRAJECTORY_ID-VAL
          RELATIVE_TO_TRAJECTORY_ID
          STATUS-VAL
          STATUS
          TRAJECTORY_ID-VAL
          TRAJECTORY_ID
))