/* This file is autogenerated, do not edit*/
#include "moc_obstacles_display.cpp"
#include "moc_obstacle_extractor_panel.cpp"
#include "moc_obstacle_publisher_panel.cpp"
#include "moc_obstacle_tracker_panel.cpp"
#include "moc_scans_merger_panel.cpp"
